// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUKsO5c3rptTVJhU6P-pkAfIm5mPNfpjQ',
    appId: '1:831206923918:web:069c360e827f8f268633df',
    messagingSenderId: '831206923918',
    projectId: 'intec-social-app-f1408',
    authDomain: 'intec-social-app-f1408.firebaseapp.com',
    storageBucket: 'intec-social-app-f1408.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_4jEaYGZBHust7oHFW238-VdJUdRW1A',
    appId: '1:831206923918:android:bb14e4aa664f5cc98633df',
    messagingSenderId: '831206923918',
    projectId: 'intec-social-app-f1408',
    storageBucket: 'intec-social-app-f1408.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUKsO5c3rptTVJhU6P-pkAfIm5mPNfpjQ',
    appId: '1:831206923918:web:9f773288deea73db8633df',
    messagingSenderId: '831206923918',
    projectId: 'intec-social-app-f1408',
    authDomain: 'intec-social-app-f1408.firebaseapp.com',
    storageBucket: 'intec-social-app-f1408.firebasestorage.app',
  );
}
